import type { ProductDetailConfig } from "@/lib/product-detail";

const volumeQuantities = ["50–499 pcs", "500–2,999 pcs", "3,000–4,999 pcs", "5,000+ pcs"] as const;

const gallery = (slug: string, alts: readonly string[]) =>
  alts.map((alt, index) => ({
    src: `/products/${slug}/${String(index + 1).padStart(2, "0")}-${index === 0 ? "hero" : "detail"}.webp`,
    alt,
  }));

export const jmz729s: ProductDetailConfig = {
  slug: "jmz-729s",
  model: "JMZ-729S",
  category: "Neck & Shoulder",
  name: "Contoured Electric Neck Massage Pillow",
  eyebrow: "OEM / ODM MASSAGE PILLOW",
  description: "A full-size contoured neck pillow combining three massage programs, two warming levels and a rechargeable integrated control design for reclining relaxation.",
  seoDescription: "Explore the JMZ-729S contoured electric neck massage pillow with three massage programs, two heating levels, a removable cover and OEM/ODM options.",
  badges: ["3 Massage Modes", "2 Heat Levels", "2000mAh Battery", "Removable Cover"],
  gallery: gallery("jmz-729s", [
    "JMZ-729S cream contoured electric neck massage pillow",
    "JMZ-729S massage pillow presented in its retail box",
    "Three-quarter view of the JMZ-729S neck massage pillow",
    "JMZ-729S side control panel and USB-C charging port",
    "Front structure of the JMZ-729S contoured massage pillow",
    "Side profile of the JMZ-729S electric neck pillow",
    "JMZ-729S removable cover zipper detail",
    "JMZ-729S neck massage pillow in reclining use",
    "Rear view of the JMZ-729S cream massage pillow",
    "Opposite side view of the JMZ-729S massage pillow",
  ]),
  priceRange: "US$28.30–32.00 / pc",
  moq: "MOQ 50 pcs",
  samplePrice: "US$36",
  priceTiers: volumeQuantities.map((quantity, index) => ({ quantity, price: ["US$32.00 / pc", "US$30.50 / pc", "US$29.50 / pc", "US$28.30 / pc"][index] })),
  featuresLabel: "Core functions",
  featuresTitle: "Contoured Support with Integrated Massage",
  featuresIntro: "The supplied JMZ-729S information confirms three massage programs, two warming levels and a rechargeable control system built into the pillow.",
  features: [
    { title: "Three massage programs", copy: "Combined, concentrated and circular massage modes provide three distinct operating patterns." },
    { title: "Two warming levels", copy: "A dedicated heating button gives direct access to two selectable warming settings." },
    { title: "Contoured neck support", copy: "Raised sides and a curved center support the head and neck during reclining use." },
    { title: "Removable zippered cover", copy: "The outer cover can be accessed through the side zipper for easier product care." },
  ],
  specsIntro: "The following operating, electrical and dimensional information comes from the supplied product sheet and product selling points.",
  specs: [
    { item: "Model", value: "JMZ-729S", status: "Confirmed" },
    { item: "Product Type", value: "Contoured electric neck massage pillow", status: "Confirmed" },
    { item: "Massage Programs", value: "Combined / concentrated / circular; 3 modes", status: "Confirmed" },
    { item: "Heating", value: "2 levels", status: "Confirmed" },
    { item: "Battery", value: "2000mAh rechargeable battery", status: "Confirmed" },
    { item: "Rated Input", value: "5 V / 2 A", status: "Confirmed" },
    { item: "Rated Power", value: "10 W", status: "Confirmed" },
    { item: "Charging", value: "Integrated USB-C charging port", status: "Confirmed" },
    { item: "Control Method", value: "Side button control", status: "Confirmed" },
    { item: "Product Size", value: "580 × 440 × 120 mm", status: "Confirmed" },
    { item: "Color Box Size", value: "585 × 145 × 440 mm", status: "Confirmed" },
    { item: "Shown Color", value: "Cream / ivory", status: "Confirmed" },
  ],
  inquiryCopy: "Tell us your order quantity, destination market and customization requirements. Our team will confirm availability, branding and packing details with the quotation.",
};

export const jmz908: ProductDetailConfig = {
  slug: "jmz-908",
  model: "JMZ-908",
  category: "Eye Care",
  name: "EMS Air Compression Eye Massager with Heat",
  eyebrow: "CUSTOM OEM / ODM EYE MASSAGER",
  description: "A rechargeable wraparound eye massager combining three air-compression modes, two heating levels, EMS microcurrent and vibration in a padded design.",
  seoDescription: "Explore the customizable JMZ-908 rechargeable eye massager with air compression, heating, EMS microcurrent, vibration and OEM/ODM options.",
  badges: ["3 Air Modes", "2 Heat Levels", "EMS", "Vibration"],
  gallery: gallery("jmz-908", [
    "JMZ-908 ivory rechargeable EMS air compression eye massager",
    "JMZ-908 padded pulse massage eye mask",
    "JMZ-908 eye massager shown in a relaxation setting",
    "Inside contact surface of the JMZ-908 eye massager",
    "Front view of the JMZ-908 pulse eye massage mask",
    "Rear fastening band of the JMZ-908 eye massager",
    "Side profile of the JMZ-908 eye massager",
    "JMZ-908 eye massager with retail packaging",
  ]),
  customPricing: true,
  featuresLabel: "Custom configuration",
  featuresTitle: "Four Comfort Technologies in One Eye Mask",
  featuresIntro: "The supplied selling points confirm air compression, heating, EMS and vibration. Final pricing is prepared according to the selected configuration and customization scope.",
  features: [
    { title: "Three air-compression modes", copy: "Three selectable patterns provide different air-compression experiences around the eye area." },
    { title: "Two heating levels", copy: "Choose approximately 36°C or 42°C warming, or switch the heating function off." },
    { title: "EMS + vibration", copy: "EMS microcurrent and vibration add two separately controlled massage functions." },
    { title: "15-minute cycle", copy: "Each operating session follows a defined 15-minute cycle for straightforward use." },
  ],
  specsIntro: "Confirmed functional details are listed below. Commercial terms will be finalized for the required OEM/ODM configuration.",
  specs: [
    { item: "Model", value: "JMZ-908", status: "Confirmed" },
    { item: "Product Type", value: "Rechargeable wraparound eye massager", status: "Confirmed" },
    { item: "Air Compression", value: "3 selectable modes", status: "Confirmed" },
    { item: "Heating", value: "Approx. 36°C / 42°C / off", status: "Confirmed" },
    { item: "EMS", value: "Dedicated microcurrent function", status: "Confirmed" },
    { item: "Vibration", value: "Independent vibration control", status: "Confirmed" },
    { item: "Operating Cycle", value: "15 minutes", status: "Confirmed" },
    { item: "Battery", value: "1200mAh rechargeable battery", status: "Confirmed" },
    { item: "Controls", value: "Three-button side control panel", status: "Confirmed" },
    { item: "Fit", value: "Padded wraparound design with rear fastening band", status: "Confirmed" },
    { item: "Price / MOQ", value: "Customized quotation based on project requirements", status: "TBC" },
  ],
  inquiryCopy: "Tell us the functions, quantity, target market, logo and packaging you need. Our team will prepare a project-based custom quotation.",
};

export const jmz802: ProductDetailConfig = {
  slug: "jmz-802",
  model: "JMZ-802",
  category: "Hand & Wrist",
  name: "3-in-1 Air Pressure Hand & Wrist Massager",
  eyebrow: "OEM / ODM HAND MASSAGER",
  description: "A rechargeable hand and wrist wellness massager combining five-level air pressure, bidirectional kneading and three-level warming in a compact fabric-covered device.",
  seoDescription: "Explore the JMZ-802 hand and wrist massager with five pressure levels, bidirectional kneading, three heat levels and OEM/ODM options.",
  badges: ["5 Pressure Levels", "3-Speed Kneading", "3 Heat Levels", "2000mAh Battery"],
  gallery: gallery("jmz-802", [
    "Blue JMZ-802 air pressure hand and wrist massager",
    "Front structure of the JMZ-802 hand massager",
    "JMZ-802 control-side view",
    "Opposite side of the JMZ-802 hand massager",
    "Top view of the JMZ-802 wrist opening",
    "Bottom construction of the JMZ-802 hand massager",
    "Close-up of the JMZ-802 three-button control panel",
    "JMZ-802 used for a wrist relaxation session",
    "JMZ-802 fabric, seam and zipper detail",
    "JMZ-802 air pressure, kneading and heating functions",
  ]),
  priceRange: "US$13.30–15.10 / pc",
  moq: "MOQ 50 pcs",
  samplePrice: "US$18.50",
  priceTiers: volumeQuantities.map((quantity, index) => ({ quantity, price: ["US$15.10 / pc", "US$14.50 / pc", "US$13.80 / pc", "US$13.30 / pc"][index] })),
  featuresLabel: "Core functions",
  featuresTitle: "Adjustable Pressure, Kneading and Warmth",
  featuresIntro: "JMZ-802 combines three separately adjustable wellness functions with a rechargeable cordless design and a simple three-button control panel.",
  features: [
    { title: "Five pressure levels", copy: "Five selectable air-pressure settings range from gentle to stronger compression." },
    { title: "Bidirectional kneading", copy: "Three kneading speeds alternate forward and reverse rotation at approximately five-second intervals." },
    { title: "Three warming levels", copy: "Choose nominal warming settings of approximately 40°C, 45°C or 50°C." },
    { title: "15-minute cycle", copy: "The defined operating cycle supports short, consistent daily wellness sessions." },
  ],
  specsIntro: "Electrical, operating, product and carton data below come from the supplied product sheet and selling-point document.",
  specs: [
    { item: "Model", value: "JMZ-802", status: "Confirmed" },
    { item: "Product Type", value: "Air-pressure hand and wrist massager", status: "Confirmed" },
    { item: "Functions", value: "Air pressure / bidirectional kneading / warming", status: "Confirmed" },
    { item: "Air Pressure", value: "5 levels", status: "Confirmed" },
    { item: "Kneading", value: "3 speeds with alternating direction", status: "Confirmed" },
    { item: "Heating", value: "Approx. 40°C / 45°C / 50°C", status: "Confirmed" },
    { item: "Operating Cycle", value: "15 minutes", status: "Confirmed" },
    { item: "Battery", value: "2000mAh rechargeable battery", status: "Confirmed" },
    { item: "Rated Input / Power", value: "DC 5 V / 1 A; 5 W", status: "Confirmed" },
    { item: "Charging", value: "USB-C; specified charging time under 3.5 hours", status: "Confirmed" },
    { item: "Product Size / N.W.", value: "170 × 110 × 140 mm; 660 g", status: "Confirmed" },
    { item: "Color Box", value: "212 × 176 × 116 mm", status: "Confirmed" },
    { item: "Master Carton", value: "370 × 450 × 520 mm; 16 pcs; G.W. 17.04 kg", status: "Confirmed" },
  ],
  inquiryCopy: "Tell us your order quantity, market and customization requirements. Our team will confirm branding, packaging, lead time and shipping details with the quotation.",
};

export const jmz903: ProductDetailConfig = {
  slug: "jmz-903",
  model: "JMZ-903",
  category: "Body Care",
  name: "3-in-1 Suction, Heat & EMS Gua Sha Massager",
  eyebrow: "OEM / ODM BODY MASSAGER",
  description: "A portable body-care device combining 12-level suction, adjustable warming and 12-level EMS with a wide eight-point contact head and clear digital display.",
  seoDescription: "Explore the JMZ-903 suction, heat and EMS gua sha massager with 12-level controls, a 20-minute cycle and OEM/ODM options.",
  badges: ["12-Level Suction", "41–48°C Heat", "12-Level EMS", "20-Min Auto-Off"],
  gallery: gallery("jmz-903", [
    "White JMZ-903 suction heat and EMS gua sha massager",
    "Front structure of the JMZ-903 handheld body massager",
    "Rear and side view of the JMZ-903",
    "JMZ-903 wide eight-point working head",
    "JMZ-903 USB-C charging port detail",
    "JMZ-903 button control panel and display",
    "JMZ-903 suction, heating and EMS functions",
    "JMZ-903 levels, timer and temperature overview",
    "JMZ-903 standard packaging contents",
    "JMZ-903 used on the shoulder area",
  ]),
  priceRange: "US$8.40–9.40 / pc",
  moq: "MOQ 50 pcs",
  samplePrice: "US$14",
  priceTiers: volumeQuantities.map((quantity, index) => ({ quantity, price: ["US$9.40 / pc", "US$9.00 / pc", "US$8.60 / pc", "US$8.40 / pc"][index] })),
  featuresLabel: "Core functions",
  featuresTitle: "Three Adjustable Body-Care Functions",
  featuresIntro: "The JMZ-903 combines suction, warming and EMS in one rechargeable device, with independent 0–12 controls and a 20-minute automatic working cycle.",
  features: [
    { title: "12-level suction", copy: "Select levels 1–12 for different body areas, or choose level 0 to switch suction off." },
    { title: "41–48°C warming", copy: "Twelve selectable heat levels support adjustable warming, with level 0 turning heat off." },
    { title: "12-level EMS", copy: "EMS intensity can be adjusted from level 1 to 12 and switched off independently at level 0." },
    { title: "Digital 20-minute cycle", copy: "The display shows settings and remaining time before automatic shutoff at the end of the cycle." },
  ],
  specsIntro: "The following technical details come from the supplied specification sheet, function manual and real-product references.",
  specs: [
    { item: "Model", value: "JMZ-903", status: "Confirmed" },
    { item: "Product Type", value: "Rechargeable suction, heat and EMS body massager", status: "Confirmed" },
    { item: "Functions", value: "Suction / warming / EMS", status: "Confirmed" },
    { item: "Suction", value: "0–12 levels", status: "Confirmed" },
    { item: "Heating", value: "0–12 levels; approx. 41–48°C", status: "Confirmed" },
    { item: "EMS", value: "0–12 levels", status: "Confirmed" },
    { item: "Operating Cycle", value: "20 minutes with automatic shutoff", status: "Confirmed" },
    { item: "Battery", value: "3.7 V / 2000mAh rechargeable battery", status: "Confirmed" },
    { item: "Rated Input / Power", value: "DC 5 V / 2 A; 10 W", status: "Confirmed" },
    { item: "Charging", value: "USB-C; specified charging time under 4.5 hours", status: "Confirmed" },
    { item: "Product Size / N.W.", value: "90 × 90 × 200 mm; 300 g", status: "Confirmed" },
    { item: "Control Method", value: "Button control with digital status display", status: "Confirmed" },
  ],
  inquiryCopy: "Tell us your quantity, destination market and customization requirements. Our team will confirm branding, packaging and final commercial terms with the quotation.",
};

export const newProductDetails = [jmz729s, jmz908, jmz802, jmz903] as const;
