import type { ProductDetailConfig } from "@/lib/product-detail";

const quantities = ["50–499 pcs", "500–2,999 pcs", "3,000–4,999 pcs", "5,000+ pcs"] as const;

const gallery = (slug: string, alts: readonly string[]) =>
  alts.map((alt, index) => ({
    src: `/products/${slug}/${String(index + 1).padStart(2, "0")}-${index === 0 ? "hero" : "detail"}.webp`,
    alt,
  }));

const tiers = (prices: readonly string[]) =>
  quantities.map((quantity, index) => ({ quantity, price: `US$${prices[index]} / pc` }));

export const jmz807p: ProductDetailConfig = {
  slug: "jmz-807p",
  model: "JMZ-807P",
  category: "Neck & Shoulder",
  name: "Cloud Plus Heated Neck Massage Pillow",
  eyebrow: "OEM / ODM NECK MASSAGE PILLOW",
  description: "A compact rechargeable neck massage pillow with three massage modes, three warming levels and layered padded contact panels.",
  seoDescription: "Explore the JMZ-807P Cloud Plus neck massage pillow with three massage modes, three heat levels, a rechargeable battery and OEM/ODM options.",
  badges: ["3 Massage Modes", "3 Heat Levels", "2600mAh Battery", "15-Min Auto-Off"],
  gallery: gallery("jmz-807p", [
    "JMZ-807P navy and cream Cloud Plus neck massage pillow",
    "Front view of the JMZ-807P neck massage pillow",
    "Top structure and layered contact panels of the JMZ-807P",
    "JMZ-807P side control panel and charging port",
    "Rear adjustable strap of the JMZ-807P",
    "Close-up of the JMZ-807P layered neck-contact pads",
    "Three massage modes of the JMZ-807P",
    "Three warming levels of the JMZ-807P",
    "JMZ-807P controls and rechargeable power",
    "JMZ-807P dimensions and supplied accessories",
    "JMZ-807P neck massage pillow in use",
  ]),
  priceRange: "US$19.60–23.90 / pc",
  moq: "MOQ 50 pcs",
  samplePrice: "US$27.50",
  priceTiers: tiers(["23.90", "22.20", "20.50", "19.60"]),
  featuresLabel: "Core functions",
  featuresTitle: "Layered Neck Comfort with Adjustable Warmth",
  featuresIntro: "The supplied product notes describe three massage programs, three warming settings and a compact cordless design for reclining use.",
  features: [
    { title: "Three massage modes", copy: "Relax, Acupressure and Vitality offer three selectable massage patterns." },
    { title: "Three warming levels", copy: "Choose a nominal setting of 38°C, 40°C or 45°C to suit personal comfort." },
    { title: "Layered contact panels", copy: "Symmetrical padded panels surround the neck while the middle section supports the back of the neck." },
    { title: "15-minute cycle", copy: "The pillow switches off automatically after approximately 15 minutes of operation." },
  ],
  specsIntro: "The following values come from the supplied English selling points and product image set.",
  specs: [
    { item: "Model", value: "JMZ-807P", status: "Confirmed" },
    { item: "Product Type", value: "Rechargeable neck massage pillow", status: "Confirmed" },
    { item: "Massage Modes", value: "Relax / Acupressure / Vitality", status: "Confirmed" },
    { item: "Warming", value: "3 levels: 38°C / 40°C / 45°C nominal", status: "Confirmed" },
    { item: "Operating Cycle", value: "Approx. 15 minutes with automatic shut-off", status: "Confirmed" },
    { item: "Battery", value: "3.7 V / 2600mAh rechargeable battery", status: "Confirmed" },
    { item: "Rated Input", value: "5 V / 2 A; USB-C charging", status: "Confirmed" },
    { item: "Controls", value: "Three-button side panel", status: "Confirmed" },
    { item: "Product Size", value: "300 × 270 × 130 mm", status: "Confirmed" },
    { item: "Rear Strap", value: "Adjustable woven strap and buckle", status: "Confirmed" },
  ],
  inquiryCopy: "Tell us your quantity, target market and branding or packaging requirements. Our team will confirm the final commercial terms with your quotation.",
};

export const jmz706w: ProductDetailConfig = {
  slug: "jmz-706w",
  model: "JMZ-706W",
  category: "Neck & Shoulder",
  name: "4-Point Heated Neck & Trapezius Massage Pillow",
  eyebrow: "OEM / ODM NECK MASSAGE PILLOW",
  description: "A rechargeable four-point kneading pillow with four massage modes, three speeds and two warming levels for neck and upper-shoulder relaxation.",
  seoDescription: "Explore the JMZ-706W four-point neck and trapezius massage pillow with bidirectional kneading, two heat levels and USB-C charging.",
  badges: ["4-Point Kneading", "4 Massage Modes", "3 Speeds", "2 Heat Levels"],
  gallery: gallery("jmz-706w", [
    "JMZ-706W cream and blue four-point neck massage pillow",
    "Three-quarter side view of the JMZ-706W",
    "JMZ-706W neck and shoulder use scene",
    "Four-point massage structure of the JMZ-706W",
    "JMZ-706W bidirectional kneading illustration",
    "Two warming levels of the JMZ-706W",
    "Four massage modes and three speeds of the JMZ-706W",
    "Four-button control panel on the JMZ-706W",
    "USB-C charging and battery information for JMZ-706W",
    "JMZ-706W dimensions and specifications",
  ]),
  priceRange: "US$17.80–21.00 / pc",
  moq: "MOQ 50 pcs",
  samplePrice: "US$25.00",
  priceTiers: tiers(["21.00", "19.50", "18.00", "17.80"]),
  featuresLabel: "Core functions",
  featuresTitle: "Focused Four-Point Kneading",
  featuresIntro: "Two larger and two smaller massage contacts work across the neck and trapezius area, with selectable speed, program and warmth.",
  features: [
    { title: "Four-point contact", copy: "Two large and two smaller contacts create focused coverage across the neck and upper shoulders." },
    { title: "Bidirectional kneading", copy: "Forward, reverse and alternating rotation patterns vary the massage feel." },
    { title: "Four modes, three speeds", copy: "Select one of four massage programs and three speed settings." },
    { title: "Two-level warmth", copy: "Adjust the heat separately with the dedicated control button." },
  ],
  specsIntro: "Operating and dimensional details come from the supplied English selling points and product visuals.",
  specs: [
    { item: "Model", value: "JMZ-706W", status: "Confirmed" },
    { item: "Product Type", value: "Rechargeable neck and trapezius massage pillow", status: "Confirmed" },
    { item: "Massage Contacts", value: "4 points: 2 large and 2 small", status: "Confirmed" },
    { item: "Massage Modes / Speeds", value: "4 modes / 3 speeds", status: "Confirmed" },
    { item: "Kneading", value: "Forward / reverse / alternating rotation", status: "Confirmed" },
    { item: "Heating", value: "2 levels", status: "Confirmed" },
    { item: "Battery", value: "7.4 V / 3500mAh rechargeable battery", status: "Confirmed" },
    { item: "Rated Input / Power", value: "5 V / 2 A; 10 W", status: "Confirmed" },
    { item: "Charging", value: "USB-C", status: "Confirmed" },
    { item: "Controls", value: "Four-button side panel", status: "Confirmed" },
    { item: "Product Size", value: "335 × 275 × 175 mm", status: "Confirmed" },
  ],
  inquiryCopy: "Tell us your quantity, destination market and OEM/ODM requirements. Our team will confirm branding, packaging and final commercial terms.",
};

export const jmz706h: ProductDetailConfig = {
  slug: "jmz-706h",
  model: "JMZ-706H",
  category: "Neck & Shoulder",
  name: "Cordless 4-Point Heated Neck Massage Pillow",
  eyebrow: "OEM / ODM NECK MASSAGE PILLOW",
  description: "A four-point kneading massage pillow with four modes, three intensity levels, two warming settings and an adjustable chair strap.",
  seoDescription: "Explore the JMZ-706H cordless neck and shoulder massage pillow with four-point kneading, adjustable heat and a secure chair strap.",
  badges: ["4-Point Kneading", "4 Massage Modes", "3 Intensity Levels", "2 Heat Levels"],
  gallery: gallery("jmz-706h", [
    "JMZ-706H cream and orange four-point neck massage pillow",
    "Four-point kneading illustration for JMZ-706H",
    "Four massage modes of the JMZ-706H",
    "Three intensity levels of the JMZ-706H",
    "Two heat levels of the JMZ-706H",
    "JMZ-706H neck and shoulder comfort illustration",
    "JMZ-706H used on a high-back sofa",
    "JMZ-706H for multiple massage positions",
    "Human-like kneading illustration for JMZ-706H",
    "JMZ-706H cordless battery and Type-C charging",
    "Adjustable chair strap of the JMZ-706H",
  ]),
  priceRange: "US$21.50–26.00 / pc",
  moq: "MOQ 50 pcs",
  samplePrice: "US$30.00",
  priceTiers: tiers(["26.00", "23.50", "22.00", "21.50"]),
  featuresLabel: "Core functions",
  featuresTitle: "Adjustable Kneading for Neck and Back",
  featuresIntro: "The supplied JMZ-706H selling points describe four contact heads, flexible massage settings and an adjustable chair strap.",
  features: [
    { title: "Four-point massage", copy: "Two larger and two smaller heads target the neck, shoulders and upper back." },
    { title: "Four modes", copy: "Four selectable massage patterns vary the rhythm of the kneading motion." },
    { title: "Three intensity levels", copy: "Adjust the massage pressure from gentler to stronger operation." },
    { title: "Two warming levels", copy: "Add a selectable warming setting during a massage session." },
  ],
  specsIntro: "Confirmed features come from the supplied selling-point document and images. Unprovided technical values remain open for confirmation.",
  specs: [
    { item: "Model", value: "JMZ-706H", status: "Confirmed" },
    { item: "Product Type", value: "Cordless neck and shoulder massage pillow", status: "Confirmed" },
    { item: "Massage Contacts", value: "4 heads: 2 large and 2 small", status: "Confirmed" },
    { item: "Massage Modes", value: "4 modes", status: "Confirmed" },
    { item: "Intensity", value: "3 levels", status: "Confirmed" },
    { item: "Heating", value: "2 levels", status: "Confirmed" },
    { item: "Battery", value: "3500mAh rechargeable battery", status: "Confirmed" },
    { item: "Charging", value: "USB-C / Type-C", status: "Confirmed" },
    { item: "Controls", value: "Four buttons for power, mode, intensity and heat", status: "Confirmed" },
    { item: "Chair Strap", value: "Adjustable elastic strap", status: "Confirmed" },
    { item: "Product Size / Rated Input", value: "To be confirmed", status: "TBC" },
  ],
  inquiryCopy: "Tell us your target quantity, market and preferred branding or packaging. Our team will confirm the remaining technical and commercial details.",
};

export const jmz901: ProductDetailConfig = {
  slug: "jmz-901",
  model: "JMZ-901",
  category: "Head & Scalp",
  name: "Rotating EMS Scalp Massager with LED Light",
  eyebrow: "OEM / ODM SCALP MASSAGER",
  description: "A handheld scalp massager shown with rotating brush contacts, two EMS levels, red LED light and a refillable 5 mL ampoule tank.",
  seoDescription: "Explore the JMZ-901 handheld scalp massager with two-speed rotation, two EMS levels, red LED light, a 5 mL refillable tank and USB-C charging.",
  badges: ["2-Speed Rotation", "2-Level EMS", "Red LED Light", "5 mL Tank"],
  gallery: gallery("jmz-901", [
    "JMZ-901 white handheld rotating scalp massager",
    "Front structure of the JMZ-901 scalp massager",
    "Rear view of the JMZ-901 massager and ampoule fitting",
    "Side profile of the JMZ-901 scalp massager",
    "Close-up of the JMZ-901 brush and contact head",
    "JMZ-901 refillable 5 mL ampoule tank diagram",
    "Two-button control of the JMZ-901",
    "JMZ-901 Type-C charging and battery information",
    "JMZ-901 rotation, EMS and red LED functions",
    "JMZ-901 scalp massager shown in use",
  ]),
  priceRange: "US$14.80–19.00 / pc",
  moq: "MOQ 50 pcs",
  samplePrice: "US$30.00",
  priceTiers: tiers(["19.00", "17.00", "15.30", "14.80"]),
  featuresLabel: "Core functions",
  featuresTitle: "Rotation, EMS and Scalp-Care Accessories",
  featuresIntro: "The supplied product visuals identify the main functions and components shown here. Electrical and dimensional data beyond those visuals still need confirmation.",
  features: [
    { title: "Two-speed rotation", copy: "Choose between two rotation speeds for the brush head." },
    { title: "Two EMS levels", copy: "The illustrated control panel provides two selectable EMS levels." },
    { title: "Red LED light", copy: "Red LED light is integrated into the working head." },
    { title: "Refillable 5 mL tank", copy: "A removable ampoule tank is shown with a 5 mL capacity." },
  ],
  specsIntro: "These details are taken from the supplied product visuals. Please confirm the final technical sheet before relying on unlisted values.",
  specs: [
    { item: "Model", value: "JMZ-901", status: "Confirmed" },
    { item: "Product Type", value: "Handheld scalp massager", status: "Confirmed" },
    { item: "Rotation", value: "2 speeds", status: "Confirmed" },
    { item: "EMS", value: "2 levels", status: "Confirmed" },
    { item: "Light", value: "Red LED", status: "Confirmed" },
    { item: "Ampoule Tank", value: "Refillable 5 mL tank", status: "Confirmed" },
    { item: "Controls", value: "Two-button panel", status: "Confirmed" },
    { item: "Battery", value: "2000mAh rechargeable battery", status: "Confirmed" },
    { item: "Charging", value: "USB-C; supplied visual states under 4 hours", status: "Confirmed" },
    { item: "Product Size / Rated Input", value: "To be confirmed", status: "TBC" },
  ],
  inquiryCopy: "Tell us your order quantity, target market and any branding or packaging needs. Our team will confirm the full specifications and quotation.",
};

export const plannedProductDetails = [jmz807p, jmz706w, jmz706h, jmz901] as const;
