'use client';

import { FormEvent, useState } from 'react';
import { usePathname } from 'next/navigation';
import { companyFacts, contactLinks } from '@/lib/company';
import { operationalClaims } from '@/lib/operational-claims';
import { trackConversionEvent } from '@/lib/analytics';

const whatsappMessage = 'Hello JAMOOZ, I am interested in your massage products and OEM/ODM services. Please share more information.';
const whatsappUrl = contactLinks.whatsapp(whatsappMessage);

const fields = [
  { name: 'name', label: 'Name', type: 'text', required: true }, { name: 'company', label: 'Company', type: 'text', required: true },
  { name: 'email', label: 'Business Email', type: 'email', required: true }, { name: 'phone', label: 'WhatsApp / Phone', type: 'tel', required: false },
  { name: 'product', label: 'Product Interested In', type: 'text', required: true }, { name: 'quantity', label: 'Estimated Quantity', type: 'text', required: false },
] as const;

export default function PreviewContactSection() {
  const pathname = usePathname(); const [prepared, setPrepared] = useState(false); if (pathname !== '/' && !pathname.startsWith('/preview')) return null;
  const handleSubmit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const body = [`Name: ${data.get('name')}`, `Company: ${data.get('company')}`, `Business Email: ${data.get('email')}`, `WhatsApp / Phone: ${data.get('phone') || 'Not provided'}`, `Product Interested In: ${data.get('product')}`, `Estimated Quantity: ${data.get('quantity') || 'Not provided'}`, `OEM / ODM Requirement: ${data.get('oem')}`, '', 'Message:', String(data.get('message') || '')].join('\n'); trackConversionEvent('form_submit', { form_id: 'preview-inquiry-form', form_method: 'mailto' }); setPrepared(true); window.location.href = `${contactLinks.email}?subject=${encodeURIComponent('JAMOOZ B2B Request for Quote')}&body=${encodeURIComponent(body)}`; };
  return (
    <section id="inquiry" className="scroll-mt-24 bg-gradient-to-br from-[#151028] via-[#211345] to-[#3d1a6d] py-16 text-white md:py-24">
      <div className="mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 lg:grid-cols-[1.45fr_.75fr] lg:px-8"><div><p className="text-xs font-black uppercase tracking-[0.24em] text-violet-300">Inquiry / Request A Quote</p><h2 className="mt-4 text-4xl font-black tracking-tight md:text-5xl">Tell us what you want to build.</h2><p className="mt-4 max-w-2xl leading-7 text-white/65">Share your product, volume and customization requirements. This preview prepares a complete inquiry in your email app so you can review it before sending.</p>
        <form id="preview-inquiry-form" onSubmit={handleSubmit} className="mt-10 grid gap-5 sm:grid-cols-2">{fields.map((field) => <label key={field.name} className="text-xs font-bold uppercase tracking-wider text-white/70">{field.label}{field.required && ' *'}<input name={field.name} type={field.type} required={field.required} data-clarity-mask="true" className="mt-2 w-full rounded-xl border border-white/15 bg-white/10 px-4 py-3.5 text-sm font-normal normal-case tracking-normal text-white outline-none focus:border-violet-300 focus:bg-white/15" /></label>)}<label className="text-xs font-bold uppercase tracking-wider text-white/70 sm:col-span-2">OEM / ODM Requirement<select name="oem" defaultValue="No customization required" data-clarity-mask="true" className="mt-2 w-full rounded-xl border border-white/15 bg-[#2b1852] px-4 py-3.5 text-sm font-normal normal-case tracking-normal text-white outline-none"><option>No customization required</option><option>OEM — Logo / Packaging</option><option>ODM — Product Customization</option><option>Not sure — Need recommendation</option></select></label><label className="text-xs font-bold uppercase tracking-wider text-white/70 sm:col-span-2">Message<textarea name="message" rows={5} data-clarity-mask="true" className="mt-2 w-full resize-y rounded-xl border border-white/15 bg-white/10 px-4 py-3.5 text-sm font-normal normal-case tracking-normal text-white outline-none focus:border-violet-300" /></label><div className="sm:col-span-2"><button type="submit" className="w-full rounded-full bg-white px-7 py-4 text-sm font-black tracking-[0.08em] text-violet-800 transition hover:-translate-y-0.5 sm:w-auto">SEND INQUIRY BY EMAIL →</button>{prepared && <p className="mt-3 text-sm text-violet-200">Your email app should now be open. Please review and send the message to {companyFacts.contact.email}.</p>}</div></form></div>
        <aside className="h-fit rounded-3xl border border-white/15 bg-white/10 p-8 backdrop-blur-sm lg:mt-20"><p className="text-xs font-black uppercase tracking-[0.22em] text-violet-300">Contact JAMOOZ</p><a href={contactLinks.email} data-analytics-location="inquiry_sidebar" className="mt-7 block break-all text-2xl font-bold hover:text-violet-200">{companyFacts.contact.email}</a><a href={whatsappUrl} data-analytics-location="inquiry_sidebar" target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-3 rounded-full bg-[#25D366] px-5 py-3 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:bg-[#20bd5a] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white"><span aria-hidden className="text-lg">●</span>Chat on WhatsApp</a><p className="mt-3 text-sm text-white/65">{companyFacts.contact.whatsappDisplay}</p><div className="mt-8 space-y-5 border-t border-white/15 pt-8 text-sm text-white/70"><p><span className="block text-xs font-bold uppercase tracking-wider text-white/40">Location</span><span className="mt-1 block text-lg text-white">{companyFacts.location.label}</span></p><p><span className="block text-xs font-bold uppercase tracking-wider text-white/40">Response</span><span className="mt-1 block text-lg text-white">{operationalClaims.responseShort}</span></p></div><p className="mt-8 rounded-2xl bg-black/15 p-4 text-xs leading-6 text-white/65">Email and WhatsApp are available for product, quotation and OEM/ODM inquiries.</p></aside></div>
      <a href={whatsappUrl} data-analytics-location="floating_button" target="_blank" rel="noreferrer" aria-label="Chat with JAMOOZ on WhatsApp" title="Chat with JAMOOZ on WhatsApp" className="fixed bottom-5 right-5 z-40 flex h-14 w-14 items-center justify-center rounded-full bg-[#25D366] text-white shadow-xl ring-4 ring-white/70 transition hover:scale-105 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-violet-300"><svg aria-hidden="true" viewBox="0 0 32 32" className="h-7 w-7 fill-current"><path d="M16 3a12.5 12.5 0 0 0-10.7 19L3.7 28l6.2-1.6A12.5 12.5 0 1 0 16 3Zm0 22.7a10.2 10.2 0 0 1-5.2-1.4l-.4-.2-3.7 1 1-3.6-.2-.4A10.2 10.2 0 1 1 16 25.7Zm5.6-7.6c-.3-.2-1.8-.9-2.1-1s-.5-.2-.7.2-.8 1-.9 1.2-.3.2-.6.1a8.3 8.3 0 0 1-2.5-1.5 9.2 9.2 0 0 1-1.7-2.1c-.2-.3 0-.5.1-.6l.5-.6.3-.5c.1-.2 0-.4 0-.6l-1-2.3c-.2-.6-.5-.5-.7-.5h-.6c-.2 0-.6.1-.9.4-.3.4-1.2 1.2-1.2 2.9s1.2 3.3 1.4 3.5c.2.2 2.4 3.7 5.9 5.2.8.3 1.5.5 2 .7.8.3 1.6.2 2.2.1.7-.1 1.8-.8 2.1-1.5.3-.7.3-1.3.2-1.5-.2-.2-.5-.3-.8-.5Z" /></svg><span className="sr-only">WhatsApp</span></a>
    </section>
  );
}
